# Generated by Django 3.0.4 on 2020-04-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expirari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=100)),
                ('numar_telefon', models.CharField(max_length=20)),
                ('numar_masina', models.CharField(blank=True, max_length=100)),
                ('tip_asigurare', models.CharField(max_length=100)),
                ('sucursala', models.CharField(max_length=100)),
                ('mesaje_trimise', models.IntegerField(blank=True, default=0)),
                ('valabilitate_sfarsit', models.DateField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
