# Generated by Django 2.2.12 on 2020-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expirari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('numar_telefon', models.CharField(max_length=20)),
                ('numar_masina', models.CharField(max_length=10)),
                ('tip_asigurare', models.CharField(max_length=20)),
                ('sucursala', models.CharField(max_length=100)),
                ('valabilitate_sfarsit', models.DateField()),
                ('mesaje_trimise', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
