# Generated by Django 3.0.4 on 2020-04-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expirari',
            old_name='name',
            new_name='nume',
        ),
    ]
