# Generated by Django 3.0.4 on 2020-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20200409_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirari',
            name='numar_masina',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expirari',
            name='tip_asigurare',
            field=models.CharField(max_length=100),
        ),
    ]
