# Generated by Django 3.0.4 on 2020-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20200411_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirari',
            name='numar_masina',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
