# Generated by Django 3.0.4 on 2020-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20200411_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirari',
            name='user',
            field=models.CharField(default='Andrei', max_length=100),
            preserve_default=False,
        ),
    ]
